language: node_js
node_js:
  - 13

services:
  - docker
  
  # Pre-testing installs
install:
  - echo "nothing needs to be installed"
#npm install -f

# Scripts to be run such as tests
before_script:
  - echo "no tests"
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  # Tagging
  - docker tag udagram-api-feed sapphire001/udagram-api-feed:v1
  - docker tag udagram-api-user sapphire001/udagram-api-user:v1
  - docker tag udagram-frontend sapphire001/udagram-frontend:v1
  - docker tag udagram-reverseproxy sapphire001/udagram-reverseproxy:v1

after_success: 
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sapphire001/udagram-api-feed:v1
  - docker push sapphire001/udagram-api-user:v1
  - docker push sapphire001/udagram-frontend:v1
  - docker push sapphire001/udagram-reverseproxy:v1

